name: Build Flutter APK's and App bundle

on:
  push:
    branches: [teste]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
   #   - run: flutter doctor -v
        
      - run: flutter pub get

      - run: flutter build ios --release


    #  - name: Build APP BUNDLE
    #    run: flutter build appbundle

 #     - name: Create Release
 #       uses: ncipollo/release-action@v1.10.0
 #       with:
 #         artifacts: "build/app/outputs/apk/release/*.apk, build/app/outputs/bundle/release/*.aab"
 #         tag: v0.0.${{ github.run_number }}
